In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

In [3]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360.0,73.0,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360.0,73.0,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360.0,73.0,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360.0,73.0,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360.0,73.0,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,1/15/2018 11:24,Standard Class

In [4]:
df.shape

(41653, 53)

In [5]:
print(df.columns. tolist())

['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41653 entries, 0 to 41652
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Type                           41653 non-null  object
 1   Days for shipping (real)       41653 non-null  int64
 2   Days for shipment (scheduled)  41653 non-null  int64
 3   Benefit per order              41653 non-null  float64
 4   Sales per customer             41653 non-null  float64
 5   Delivery Status                41653 non-null  object
 6   Late_delivery_risk             41653 non-null  int64
 7   Category Id                    41653 non-null  int64
 8   Category Name                  41653 non-null  object
 9   Customer City                  41653 non-null  object
 10  Customer Country               41653 non-null  object
 11  Customer Email                 41653 non-null  object
 12  Customer Fname                 41653 non-null  object
 13  Customer Id                    41653 non-null  int64
 14  Customer Lname                 41652 non-null  object
 15  Customer Password              41653 non-null  object
 16  Customer Segment               41653 non-null  object
 17  Customer State                 41653 non-null  object
 18  Customer Street                41653 non-null  object
 19  Customer Zipcode               41652 non-null  float64
 20  Department Id                  41653 non-null  int64
 21  Department Name                41653 non-null  object
 22  Latitude                       41653 non-null  float64
 23  Longitude                      41653 non-null  float64
 24  Market                         41653 non-null  object
 25  Order City                     41653 non-null  object
 26  Order Country                  41653 non-null  object
 27  Order Customer Id              41653 non-null  int64
 28  order date (DateOrders)        41653 non-null  object
 29  Order Id                       41653 non-null  int64
 30  Order Item Cardprod Id         41653 non-null  int64
 31  Order Item Discount            41653 non-null  float64
 32  Order Item Discount Rate       41653 non-null  float64
 33  Order Item Id                  41653 non-null  int64
 34  Order Item Product Price       41653 non-null  float64
 35  Order Item Profit Ratio        41652 non-null  float64
 36  Order Item Quantity            41652 non-null  float64
 37  Sales                          41652 non-null  float64
 38  Order Item Total               41652 non-null  float64
 39  Order Profit Per Order         41652 non-null  float64
 40  Order Region                   41652 non-null  object
 41  Order State                    41652 non-null  object
 42  Order Status                   41652 non-null  object
 43  Order Zipcode                  5400 non-null   float64
 44  Product Card Id                41652 non-null  float64
 45  Product Category Id            41652 non-null  float64
 46  Product Description            0 non-null      float64
 47  Product Image                  41652 non-null  object
 48  Product Name                   41652 non-null  object
 49  Product Price                  41652 non-null  float64
 50  Product Status                 41652 non-null  float64
 51  shipping date (DateOrders)     41652 non-null  object
 52  Shipping Mode                  41652 non-null  object
dtypes: float64(19), int64(10), object(24)
memory usage: 16.8+ MB

In [24]:
print("Rows and Columns:", df.shape)

Rows and Columns: (41653, 52)

In [25]:
missing = df.isnull().sum()

print("Missing values in each column:")
print(missing[missing > 0])

print("\nTotal missing values:", df.isnull().sum().sum())

Missing values in each column:
Order Item Profit Ratio       1
Order Item Quantity           1
Sales                         1
Order Item Total              1
Order Profit Per Order        1
Order Region                  1
Order State                   1
Order Status                  1
Product Card Id               1
Product Category Id           1
Product Image                 1
Product Name                  1
Product Price                 1
Product Status                1
shipping date (DateOrders)    1
Shipping Mode                 1
Delivery_Days                 1
dtype: int64

Total missing values: 17

In [27]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [28]:
display(df.describe())

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Product Card Id,Product Category Id,Product Price,Product Status,shipping date (DateOrders),Delivery_Days
count,41653.000000,41653.000000,41653.000000,41653.000000,41653.000000,41653.000000,41653.000000,41653.000000,41653.000000,41653.000000,...,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.0,41652,41652.000000
mean,3.496147,2.893669,21.512884,177.099094,0.574388,26.631815,6816.829280,35123.999208,4.842820,29.463014,...,0.340044,0.094091,177.097368,21.512803,571.577163,26.631422,122.331297,0.0,2016-06-07 05:32:32.853644544,3.473567
min,0.000000,0.000000,-3366.000000,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,17.982491,...,0.000000,0.000000,7.490000,-3366.000000,19.000000,2.000000,9.990000,0.0,2015-01-03 00:00:00,0.000000
25%,2.000000,2.000000,6.410000,97.489998,0.000000,17.000000,3267.000000,725.000000,4.000000,18.262947,...,0.000000,0.055266,97.489998,6.410000,365.000000,17.000000,50.000000,0.0,2015-09-11 15:35:00,2.000000
50%,3.000000,4.000000,29.309999,142.500000,1.000000,24.000000,6552.000000,18103.000000,5.000000,32.950382,...,0.250000,0.075357,142.500000,29.309999,502.000000,24.000000,59.990002,0.0,2016-05-22 14:11:00,3.000000
75%,5.000000,4.000000,61.880001,248.960007,1.000000,36.000000,9933.000000,77520.000000,6.000000,39.056313,...,0.750000,0.145709,248.960007,61.885001,792.000000,36.000000,129.990005,0.0,2017-02-25 19:05:15,5.000000
max,6.000000,4.000000,708.750000,1759.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,1.000000,1.000000,1759.989990,708.750000,1363.000000,76.000000,1999.989990,0.0,2018-02-06 11:44:00,6.000000
std,1.604507,1.364745,106.059816,127.336779,0.494441,15.138142,4319.395908,37491.434621,1.573101,9.812543,...,0.385505,0.070747,127.337821,106.061088,314.576009,15.138111,138.180640,0.0,NaN,1.645841

In [29]:
import pandas as pd

df["order date (DateOrders)"] = pd.to_datetime(
    df["order date (DateOrders)"],
    errors="coerce"
)

df["shipping date (DateOrders)"] = pd.to_datetime(
    df["shipping date (DateOrders)"],
    errors="coerce"
)

print(df[[
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]].dtypes)

order date (DateOrders)       datetime64[ns]
shipping date (DateOrders)    datetime64[ns]
dtype: object

In [30]:
df["Delivery_Days"] = (
    df["shipping date (DateOrders)"]
    - df["order date (DateOrders)"]
).dt.days

print(df["Delivery_Days"].head())

0    3.0
1    5.0
2    4.0
3    3.0
4    2.0
Name: Delivery_Days, dtype: float64

In [31]:
df = df.dropna().copy()

print("Shape after handling missing values:", df.shape)
print("Total missing values:", df.isnull().sum().sum())

Shape after handling missing values: (41652, 52)
Total missing values: 0

In [32]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [33]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Product Card Id,Product Category Id,Product Price,Product Status,shipping date (DateOrders),Delivery_Days
count,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,...,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.000000,41652.0,41652,41652.000000
mean,3.496087,2.893643,21.512803,177.097368,0.574378,26.631422,6816.852204,35124.825074,4.842769,29.463284,...,0.340044,0.094091,177.097368,21.512803,571.577163,26.631422,122.331297,0.0,2016-06-07 05:32:32.853644544,3.473567
min,0.000000,0.000000,-3366.000000,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,17.982491,...,0.000000,0.000000,7.490000,-3366.000000,19.000000,2.000000,9.990000,0.0,2015-01-03 00:00:00,0.000000
25%,2.000000,2.000000,6.410000,97.489998,0.000000,17.000000,3266.750000,725.000000,4.000000,18.262947,...,0.000000,0.055266,97.489998,6.410000,365.000000,17.000000,50.000000,0.0,2015-09-11 15:35:00,2.000000
50%,3.000000,4.000000,29.309999,142.500000,1.000000,24.000000,6552.500000,18103.000000,5.000000,32.950382,...,0.250000,0.075357,142.500000,29.309999,502.000000,24.000000,59.990002,0.0,2016-05-22 14:11:00,3.000000
75%,5.000000,4.000000,61.885001,248.960007,1.000000,36.000000,9933.000000,77520.000000,6.000000,39.056313,...,0.750000,0.145709,248.960007,61.885001,792.000000,36.000000,129.990005,0.0,2017-02-25 19:05:15,5.000000
max,6.000000,4.000000,708.750000,1759.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,1.000000,1.000000,1759.989990,708.750000,1363.000000,76.000000,1999.989990,0.0,2018-02-06 11:44:00,6.000000
std,1.604479,1.364751,106.061088,127.337821,0.494443,15.138111,4319.445226,37491.505796,1.573084,9.812507,...,0.385505,0.070747,127.337821,106.061088,314.576009,15.138111,138.180640,0.0,NaN,1.645841

In [34]:
Q1 = df["Delivery_Days"].quantile(0.25)
Q3 = df["Delivery_Days"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df["Delivery_Days"] < lower_limit) |
    (df["Delivery_Days"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Number of Outliers:", len(outliers))

Q1: 2.0
Q3: 5.0
IQR: 3.0
Lower Limit: -2.5
Upper Limit: 9.5
Number of Outliers: 0

In [35]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[["Sales", "Order Item Quantity", "Order Item Discount"]] = scaler.fit_transform(
    df[["Sales", "Order Item Quantity", "Order Item Discount"]]
)

print(df[["Sales", "Order Item Quantity", "Order Item Discount"]].head())

      Sales  Order Item Quantity  Order Item Discount
0  0.159678                  0.0              0.02622
1  0.159678                  0.0              0.03278
2  0.159678                  0.0              0.03606
3  0.159678                  0.0              0.04588
4  0.159678                  0.0              0.05900

In [36]:
print("Final Shape:", df.shape)
print("Total Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

print("\nDate Column Types:")
print(df[["order date (DateOrders)", "shipping date (DateOrders)"]].dtypes)

Final Shape: (41652, 52)
Total Missing Values: 0
Duplicate Rows: 0

Date Column Types:
order date (DateOrders)       datetime64[ns]
shipping date (DateOrders)    datetime64[ns]
dtype: object

In [37]:
df.to_csv("DataCo_Cleaned_Preprocessed.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.